name: trigger jenkins job
on: [push]
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: --trace-ascii debugdump.txt http://www.example.com/

